### ISSUE TITLE
Define methodology to collect AF relevant patents

### ISSUE THREAD

**Issue by georgerichardson** [innovation-growth-lab/alphafold-impact#19]

**Comment by ampudia19** [comment]
The following are parts of the project for which we plan to use patents:
- Obtain patent citations to academic articles. Compare those citing AlphaFold (or citing papers that cite AF) with respect to a structural biology baseline.
- Estimate patent novelty and disruption when citing AF vis-à-vis some baseline.
### The Lens advantages
Any other databases with data on NPL (non-patent literature) citations have patents indexed, but citations are often not linked to academic papers. For example, in patent `WO2020176389A1`, there is a citation to a book chapter using abbreviations: `NAFISSI ET AL., APPL. MICROBIOL. BIOTECH., vol. 98, 2014, pages 2841 - 2851`. If a database identifies this as a NPL citation (for example, [Google Patents does](https://patents.google.com/patent/WO2020176389A1/en?oq=WO2020176389#nplCitations), or the [EPO](https://register.epo.org/application?number=EP20715527)), it is not linked to any academic material. Only The Lens has actual matches to [the scholarly content](https://www.lens.org/lens/search/scholar/list?p=0&n=100&s=date_published&d=%2B&f=false&e=false&l=en&authorField=author&dateFilterField=publishedYear&orderBy=%2Bdate_published&presentation=false&preview=true&stemmed=true&useAuthorId=false&patentCitationLensId.must=050-738-606-855-156). 

The reason why this is crucial is that for most analysis our starting point are scholarly articles, so unless we are willing to collect all patents first, and M to M match them to articles, we need to rely on The Lens.
#### Alternatives to The Lens
- **Google Patents**: We have pipelines at the ready from previous projects. It is relatively inexpensive, and better suited to bulk downloads than institutional counterparts.
- **WIPO**: They have the PATENTSCOPE [database](https://patentscope.wipo.int/search/en/search.jsf). It rarely includes citations on NPL (this feels somewhat arbitrary in the per-patent tabs), but is quite extensive at 115M patent documents.
- **EPO**: Two possible databases show relevant data: [Espacenet](https://worldwide.espacenet.com/patent/), and the [European Patent Register](https://register.epo.org/regviewer). They have [an API](https://www.epo.org/en/searching-for-patents/data/web-services/ops), which I've asked access to. They also have [bulk datasets](https://www.epo.org/en/searching-for-patents/data/bulk-data-sets), waiting for account creation to download them. Similar to Google Patents, it includes citations but lacks links to scholarly articles.
- **USPTO**: They have bulk downloads for all patents since 2001. They also have PatentsView, with [a dataset on non-patent citations](https://patentsview.org/download/data-download-tables). Again, these are not connected via their `doi` value, or other external identifiers. [GlobalDossier](https://globaldossier.uspto.gov) is extremely unreliable, and has blocked me. 
#### Notes
- Matt Marx has [an updated version](https://relianceonscience.org/patent-to-paper-citations) of his Reliance on Science dataset that runs through 2022. 
- Search functions are fairly unreliable - any searches should include versions with and without spaces (ie. WO2020176389A1 vs WO 2020 176389A1), with and without versions (WO2020176389A1 vs WO2020176389)
#### Recommendation
1. Between now and the end of the month, focus on collecting as much data as possible for 2023 from The Lens, focusing on `Field of Study` subfields relevant to us (ie. Biology) as well as relevant MeSH fields. This collection should focus on any patent application or patent publications in 2023, and target data should be research articles citing these. 
2. If time allows, extend collection efforts to 2022.
3. Use the Marx updated dataset to map paper to patent citations up to 2022. If 2. was possible, use it to validate % of matches, and gauge whether the Marx dataset is sufficient and comparable. 
4. Use dataset to construct metrics as per project objectives.

**Comment by ampudia19** [comment]
@georgerichardson can I get your quick input as to whether the recommended approach above is a sufficiently solid idea? I can write the API request pipelines for recommendation 1. latter this week. I have already downloaded papers that cite AF, papers that mention AF, and papers that cite a paper that cites AF. The focus of the work here would be to define patents that are relevant in so far as being counterfactuals / related to other aspects of biology. Thoughts?

**Comment by georgerichardson** [comment]
Thanks for writing this up. I certainly can't think of a better approach. A couple of thoughts I do have are:

1. Can the approach be tested with a very small subset (e.g. by choosing a tiny subfield much smaller than biology)
2. Similarly, what's the smallest amount of data we might need to do the comparison with the  Marx data?

Consider both of those within the timeframe available though. If the window we have is small, then we probably are best off just going straight for the biggest collection possible.

A poorer alternative could be to use one of the other databases you have mentioned, and simply try to identify only direct citations of the AF paper. This would obviously limit our analysis or opportunities for modelling significantly. But perhaps still useful depending on success with The Lens and the results from the analysis prioritisation exercise.
